// Code generated by "stringer -type=node_type,Op"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNDEFINED-0]
	_ = x[ALL-1]
	_ = x[MASTER-2]
	_ = x[WORKER-3]
	_ = x[GATEWAY-4]
}

const _node_type_name = "UNDEFINEDALLMASTERWORKERGATEWAY"

var _node_type_index = [...]uint8{0, 9, 12, 18, 24, 31}

func (i node_type) String() string {
	if i >= node_type(len(_node_type_index)-1) {
		return "node_type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _node_type_name[_node_type_index[i]:_node_type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[START-0]
	_ = x[STOP-1]
	_ = x[PAUSE-2]
	_ = x[RESUME-3]
	_ = x[SAVESTATE-4]
	_ = x[RESET-5]
	_ = x[ACPIPOWEROFF-6]
	_ = x[NOP-7]
}

const _Op_name = "STARTSTOPPAUSERESUMESAVESTATERESETACPIPOWEROFFNOP"

var _Op_index = [...]uint8{0, 5, 9, 14, 20, 29, 34, 46, 49}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
